### ISSUE TITLE
Feature Request - Add Sticky Notes

### ISSUE THREAD

**Issue by PunishedPineapple** [kalilistic/NeatNoter#1]
Something that would be super useful, imo, would be the ability to break a note out into a "sticky note" or "post-it".  This would basically add a no-titlebar, no controls window with the note text that you could place separately on your screen in order to have a small bit of text as a note to yourself without the main UI open.  Ideally you'd be able check a box to have a note become invisible (or visible too I guess) when you're in an instance.  The use case that made me want this was to have a reminder up of the next legendary node on patch day before you have them memorized, or a quick reference for aethersand node times, etc., but I could see it being useful as a reminder of mechanic positions, priority order, etc. in the current PF too.

I actually thought that there was already a plugin for this, but I can't find anything in the list.  If you're not interested, I can just make my own thing for myself, but it seemed like a natural extension of this plugin.

**Comment by karashiiro** [comment]
That’s a good idea, I’ll see what I can do!

**Comment by kalilistic** [comment]
Looking over old issues. Is this partially implemented by the "Minimal View"? Not quite the same as the original ask - but seemed a little similar.

**Comment by PunishedPineapple** [comment]
Hmmm not exactly.  Minimal view is kinda what I figured a popped-out note would look like, but the original thing that I was thinking of was the ability to be able to pop out one or more notes and put them up like you would a real sticky note, just on your screen instead of on the side of your monitor.

If you're going through and just trying to close old stuff, this isn't something that I desperately need; it just felt like a natural new feature.  Not even sure how many other people would use something like that.

**Comment by kalilistic** [comment]
Oh, I see what you mean. The pop out is definitely still missing. I'll leave this open.

**Comment by kalilistic** [comment]
I'm closing all issues as NeatNoter has been adopted by Shadow. If you are still interested in this bug/feature, [please report it on their new github repo](https://github.com/shadowkras/NeatNoter). Thanks for using NeatNoter.
