### ISSUE TITLE
Use of # in Category/Note Title causes issues

### ISSUE THREAD

**Issue by nageki** [kalilistic/NeatNoter#11]
![image](https://user-images.githubusercontent.com/75861784/139949752-fed16466-9c01-43e4-a9fc-a70381d26a15.png)

![image](https://user-images.githubusercontent.com/75861784/139949783-ecd6e102-06c0-4870-bc4a-88bd8d79e441.png)

First thing I tried was naming a couple of filler categories and the use of # in the title field will remove all text to the right of it then display like screenshot above. 
Update: This happens on all titles. 
Only fix I can figure out is remaking the category/note without #

**Comment by kalilistic** [comment]
Fixed!
