### ISSUE TITLE
Option to make it not appear upon game start up.

### ISSUE THREAD

**Issue by nyxalteria** [kalilistic/NeatNoter#13]
Basically what the title says, I checked the plugin settings in game and there wasn't an option for it. It pops up every time I start up XIV through XIV launcher. The current way to type it is typing the slash command for it but I think it would be a better qol feature if there was just a checkbox or something that could make it appear or not appear on start up.

**Comment by kalilistic** [comment]
Just pushed a new update. The current intended behavior is it remembers it's state. So if you close the game with it closed, it should be closed next time it opens....and vise versa.
