### ISSUE TITLE
Notes Are Resetting to Previous State

### ISSUE THREAD

**Issue by AppelPei** [kalilistic/NeatNoter#16]
Multiple times now, all of my notes have reset to an earlier state whenever I reopen the game. Usually, I only log out, and the plugin doesn't reset. But when I have to completely close and reopen, all of my notes will go back to how they were like a week ago. Currently, I have a note listing all of the ShB areas for side quests, and I've continued to delete ones I've done, but every time I reopen, all of them are back. Same with every other note. Only started happening in the last couple weeks or so (I believe after last patch?).

**Comment by kalilistic** [comment]
Hey, I tried deleting it myself but stayed deleted. I'll take a closer look at the code soon though too.
Are you on version v2.0.3.0? Do you see anything in your logs?

**Comment by AppelPei** [comment]
Yes I am on the most recent version. It's not that the notes themselves get deleted, but rather that the writing in them gets reset to how they were. However, I just tried to do this again today and it seems to have saved my information this time. Not sure if this means it's fixed or just didn't happen this time. I am not well versed in the plugin launcher, so how would I check my logs?

**Comment by karashiiro** [comment]
There's a log file at `%APPDATA%\XIVLauncher\dalamud.log`. Anything in it that says "Exception" or "Error" is suspect.

**Comment by AppelPei** [comment]
![46c79e1bda3204e2ee27e7b5bc90bb17](https://user-images.githubusercontent.com/95204751/144329078-dfc34258-eb37-4839-8b96-37d770d098d5.png)
I looked around and even searched for that file in the main XIVLauncher folder, but I don't see it anywhere. Is there a setting I have to enable in order to have logs saved? Also, the issue happened again today, but this time they reverted to a more recent version of my notes, only missing the stuff I added yesterday.

**Comment by karashiiro** [comment]
![image](https://user-images.githubusercontent.com/49822414/144355976-605aa308-19d5-4490-825c-4d0367c84dbb.png)
Logs are always saved, but that's your `AppData\Local` folder, not your `AppData\Roaming` folder. I was fairly certain that `%AppData%` linked to Roaming, but I guess not always? Anyways, try checking in the `Roaming` folder.

**Comment by kalilistic** [comment]
Thanks Kara!

I double checked the save logic and it's pretty simple - just saves everything on a 5s timer when the window is open so not sure yet what would cause this. Hopefully the logs will provide some hints.

https://github.com/kalilistic/NeatNoter/blob/master/src/NeatNoter/NeatNoter/Service/NotebookService.cs#L627

**Comment by AppelPei** [comment]
Sorry for the late reply. Been no-lifing Endwalker and haven't remembered to check the logs due to not being reminded with plugins down. I found the log, and searched for both "error" and "exception", but it could not find anything. With the lack of plugins, I also have no way to check to see if this is still occurring either. Would it help if I sent my whole log file or something?

**Comment by kalilistic** [comment]
Hey, no worries. A lot has chanced since you first saw this... maybe easiest is to let us know if you see it again? I'll keep an eye out for other users reporting the same.

**Comment by kalilistic** [comment]
I still couldn't replicate this on my side - but made a few changes that might help. I also added some extra logging. Let me know if you see it after the update.

**Comment by AppelPei** [comment]
Will be on the lookout for it and relay if it ever happens again. Thanks for all the responses off of minimal information!
