### ISSUE TITLE
Crashing with ctrl z.... sometimes....

### ISSUE THREAD

**Issue by Chrysheart** [kalilistic/NeatNoter#17]
Sometimes when I press ctrl z while using NeatNoter I crash. Not sure how to specifically trigger it. I tried to trigger it multiple times to learn how to consistently do it, but only managed to do it 1 more time (two crashes in total). I doubt it's a huge issue since it's so hard to even replicate, but mainly wanted to post it here in case it would help anyone. Both times I crashed I had been using escape ctrl x and ctrl z around the same time I was minimizing NeatNoter (like minimizing it and then pressing ctrl z). I also posted this in the discord for dalamud. Just figured I would post here too in case it helps. Oh, and I was also in a town where I couldn't use my mount, but had z tied to using my mount. In case that helps somehow. I will keep you updated if I manage to even have it happen again

**Comment by Chrysheart** [comment]
I just managed to do it again. Seems like it has something to do with how the bar was selected. I think I started to walk while having it selected and then went back to it and ctrl z crashed. The NeatNoter bar at the top was red at the time

**Comment by kalilistic** [comment]
I'll keep an eye out for this. The bar is always red at the top unless you've changed your dalamud settings.

**Comment by kalilistic** [comment]
I'm closing all issues as NeatNoter has been adopted by Shadow. If you are still interested in this bug/feature, [please report it on their new github repo](https://github.com/shadowkras/NeatNoter). Thanks for using NeatNoter.
