### ISSUE TITLE
Feature Request - Full Note Titles

### ISSUE THREAD

**Issue by Pawkkie** [kalilistic/NeatNoter#21]
Hello! Really love your plugin, I use it all the time. This feature request is a really small nit picky thing, but like I said I use this all the time so I figured I'd mention it in case you're interested. This is way easier conveyed in images than words though.

I keep my notes physically small on my screen, like this:
![unknown](https://user-images.githubusercontent.com/61265402/150886308-61ad08e7-a0c2-4336-a54e-1943e3452f2f.png)

But I prefer having the preview off (thanks for that last update), so it looks like this:)
![unknown](https://user-images.githubusercontent.com/61265402/150886329-c7dffa63-7369-4e4e-8f07-3e045262a5d6.png)

This feature request is to have the title of the note be allowed the full width of the NeatNoter window for its text box when content preview is turned off, so it resembles this more even at a smaller scale:
![Full](https://user-images.githubusercontent.com/61265402/150886266-90b58108-4831-4299-b516-8bd280a330d5.png)

Thanks a lot for the consideration! :)

**Comment by kalilistic** [comment]
This is now merged! Let me know how it goes.

**Comment by Pawkkie** [comment]
Oh man this is perfect, works exactly the way I wanted it to. Thanks a tonne! :D
