### ISSUE TITLE
Monospaced fonts

### ISSUE THREAD

**Issue by sunaurus** [kalilistic/NeatNoter#22]
Hey, awesome addon! Is it possible to somehow switch to a monospaced font? It would be awesome for things like markdown formatted tables.

**Comment by kalilistic** [comment]
I like the idea but might be tricky with fonts with imgui. Did you ever look into this @karashiiro?

**Comment by karashiiro** [comment]
I did not, the only thing I've ever done with fonts as loading larger ones.

**Comment by kalilistic** [comment]
I'm closing all issues as NeatNoter has been adopted by Shadow. If you are still interested in this bug/feature, [please report it on their new github repo](https://github.com/shadowkras/NeatNoter). Thanks for using NeatNoter.
