### ISSUE TITLE
Feature request - Text wrapping toggle

### ISSUE THREAD

**Issue by Horcrux** [kalilistic/NeatNoter#25]

**Comment by Horcrux** [comment]
I barely understand the stack this (or any ffxiv plugin, for that matter) uses. However, it doesn't look like imgui supports this yet https://github.com/ocornut/imgui/issues/952

**Comment by kalilistic** [comment]
I'm closing all issues as NeatNoter has been adopted by Shadow. If you are still interested in this bug/feature, [please report it on their new github repo](https://github.com/shadowkras/NeatNoter). Thanks for using NeatNoter.
