### ISSUE TITLE
FPS Drops while a Note is opened

### ISSUE THREAD

**Issue by qbzily** [kalilistic/NeatNoter#27]
As soon as a note is showing, FPS drops by a significant amount (around 40 fps for me personally). When hiding or closing the note, it reverts back to old value. Persists through restarts and fresh installs.

https://user-images.githubusercontent.com/104039763/164117594-ee3ff01b-2db9-4b5c-af01-1716a1adacc3.mp4

**Comment by kalilistic** [comment]
Note to self for later: just allocate the buffer yourself and call the ImGuiNative.igInputText()

**Comment by curtis846** [comment]
Having the same problem as well, frequently used and works fine before latest Dalamud update. Only happens when a note is opened, not in the menu / when minimized.

**Comment by Nanu308** [comment]
> Note to self for later: just allocate the buffer yourself and call the ImGuiNative.igInputText()

was this ever fixed? I currently get severe fps drop where i get halved from over 100 down to 50-60ish when i open a note :(

**Comment by kalilistic** [comment]
> was this ever fixed? I currently get severe fps drop where i get halved from over 100 down to 50-60ish when i open a note :(

Not yet. I'm not actively working on NeatNoter right now. I've posted looking for a new maintainer but no interest yet. https://github.com/kalilistic/NeatNoter/issues/28

**Comment by kalilistic** [comment]
I'm closing all issues as NeatNoter has been adopted by Shadow. If you are still interested in this bug/feature, [please report it on their new github repo](https://github.com/shadowkras/NeatNoter). Thanks for using NeatNoter.
