### ISSUE TITLE
Changable font size

### ISSUE THREAD

**Issue by Meguumee** [kalilistic/NeatNoter#30]
It is sometimes hard to see the contents of the notes, on a screen with a high resolution.
I was wondering if it is possible to change the font size of the notes taken. If not, is it possible to implement this?

**Comment by kalilistic** [comment]
I don't _think_ it's possible without loading a whole new font. You can scale the UI to make everything larger in the dalamud settings.

**Comment by kalilistic** [comment]
I'm closing all issues as NeatNoter has been adopted by Shadow. If you are still interested in this bug/feature, [please report it on their new github repo](https://github.com/shadowkras/NeatNoter). Thanks for using NeatNoter.
