### ISSUE TITLE
Feature Request(s) / Idea(s)

### ISSUE THREAD

**Issue by FantosmePhoinix** [kalilistic/NeatNoter#31]
Hello!
Sorry if this is odd or anything, super new to GitHub and not entirely sure what the etiquette is ^^;

Anyways, I was wonder if any of these would be possible:
1-Request) A "light" mode of sorts
- I'm one of the odd ones out where white/light font on dark backgrounds hurts my eyes. Wouldn't need to be a bright white, but at least a light grey with black font would be nice if possible!

2-Idea) An additional sorting option being by Category Name (ascending and descending) would be great!

3-Idea) Drag-and-drop sorting/organizing? Could be helpful if none of the available sorting options are what the user needs/wants.

4-Idea) A side bar or tabs at the top with the category names and/or colors so we can quickly swap to view only that category (or drag-and-drop new notes to that category to assign it to that category).

**Comment by kalilistic** [comment]
I'm closing all issues as NeatNoter has been adopted by Shadow. If you are still interested in this bug/feature, [please report it on their new github repo](https://github.com/shadowkras/NeatNoter). Thanks for using NeatNoter.
