### ISSUE TITLE
Suggestion: Add sort notes by date(ascending and descending)

### ISSUE THREAD

**Issue by johnysandels** [kalilistic/NeatNoter#4]
Sorting by that date modified (ascending/decending) would be really nice.

**Comment by kalilistic** [comment]
I added date modified as well as date created sorting options. This data wasn't previously stored so may have mixed results on old notes but will stored on new or edited notes from now on.

This is available on my testing repo: https://github.com/kalilistic/DalamudPluginRepo/raw/master/pluginmaster.json.
If there are no issues, will be pushed to main over next week or so.

**Comment by kalilistic** [comment]
This is now live. Let me know if any issues. Thanks!
