### ISSUE TITLE
Suggestion: Show categorized notes by clicking on the corresponding category.

### ISSUE THREAD

**Issue by johnysandels** [kalilistic/NeatNoter#5]
It would be great if categorized notes could be accessed through the category tab. The settings for the category could be accessed from a settings cog on the right side of the category instead. 

I've made an example of what I'd hope the feature would look like! 

![example](https://user-images.githubusercontent.com/79720646/128592638-c881c6d8-4ae8-4cdf-9425-4ccd4533e8f9.gif)

As you can see I can access all notes categorized under "b" all in one place.

I hope you like my suggestion!

**Comment by kalilistic** [comment]
I implemented this slightly different than above but hopefully the same idea. You can right click on a category to view all assigned notes.

This is available on my testing repo: https://github.com/kalilistic/DalamudPluginRepo/raw/master/pluginmaster.json.
If there are no issues, will be pushed to main over next week or so.

**Comment by kalilistic** [comment]
This is now live. Let me know if any issues. Thanks!
