### ISSUE TITLE
Feature Request: Add a close button

### ISSUE THREAD

**Issue by DenL** [kalilistic/NeatNoter#6]
Unless I'm missing something obvious, only way to close the note ui is to type in chat command again. Would be great to add a cross(close) button on the top right to allow us to easlily close the note ui. Thank you!

**Comment by kalilistic** [comment]
This is available on my testing repo: https://github.com/kalilistic/DalamudPluginRepo/raw/master/pluginmaster.json.
If there are no issues, will be pushed to main over next week or so.

**Comment by kalilistic** [comment]
This is now live. Let me know if any issues. Thanks!
