### ISSUE TITLE
Pressing ESC to remove focus undoes recent changes

### ISSUE THREAD

**Issue by Pyrii** [kalilistic/NeatNoter#7]
Trying to use neatnoter for lists is next to impossible lately, any time I try to tick something off and then remove focus, I try to press ESC and it undoes what I just did in the note. There needs to be a better way to remove focus, or an option to stop typing when clicking outside of neatnoter. If I suddenly needed to deal with an attacking enemy I'd be boned as I can't move or use any numbered skills.

**Comment by kalilistic** [comment]
This is available on my testing repo: https://github.com/kalilistic/DalamudPluginRepo/raw/master/pluginmaster.json.
If there are no issues, will be pushed to main over next week or so.

**Comment by kalilistic** [comment]
This is now live. Let me know if any issues. Thanks!
